"""Fill data to tables

Revision ID: dbc393d54f8a
Revises: b69cdff4ff28
Create Date: 2025-03-11 16:29:31.618828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc393d54f8a'
down_revision: Union[str, None] = 'b69cdff4ff28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cuisines_table = sa.table(
        'cuisines',
        sa.column('name', sa.String)
    )
    op.bulk_insert(
        cuisines_table,
        [
            {'name': 'Итальянская кухня'},
            {'name': 'Китайская кухня'},
            {'name': 'Русская кухня'},
            {'name': 'Японская кухня'},
            {'name': 'Грузинская кухня'},
            {'name': 'Французская кухня'},
        ]
    )

    dish_types_table = sa.table(
        'dish_types',
        sa.column('name', sa.String)
    )
    op.bulk_insert(
        dish_types_table,
        [
            {'name': 'Суп'},
            {'name': 'Салат'},
            {'name': 'Основное блюдо'},
            {'name': 'Закуска'},
            {'name': 'Десерт'},
            {'name': 'Напиток'},
        ]
    )

    hashtags_table = sa.table(
        'hashtags',
        sa.column('name', sa.String)
    )
    op.bulk_insert(
        hashtags_table,
        [
            {'name': '#вегетарианский'},
            {'name': '#быстрый'},
            {'name': '#домашний'},
            {'name': '#острый'},
            {'name': '#здоровый'},
            {'name': '#сезонный'},
        ]
    )

    users_table = sa.table(
        'users',
        sa.column('login', sa.String),
        sa.column('password', sa.String),
        sa.column('role', sa.Enum('ADMIN', 'USER', name='role', create_type=False))
    )
    op.bulk_insert(
        users_table,
        [
            {'login': 'admin',    'password': '$2b$12$pMoyJ785E6bR2sTWyXV5/OWjSGVGss4OkPx/9DYJKkudyiBKlLWuu', 'role': 'ADMIN'},
            {'login': 'olgaaa',     'password': '$2b$12$pMoyJ785E6bR2sTWyXV5/OWjSGVGss4OkPx/9DYJKkudyiBKlLWuu', 'role': 'USER'},
            {'login': 'sergey',   'password': '$2b$12$pMoyJ785E6bR2sTWyXV5/OWjSGVGss4OkPx/9DYJKkudyiBKlLWuu', 'role': 'USER'},
            {'login': 'annaaa',     'password': '$2b$12$pMoyJ785E6bR2sTWyXV5/OWjSGVGss4OkPx/9DYJKkudyiBKlLWuu', 'role': 'USER'},
            {'login': 'dmitriy',  'password': '$2b$12$pMoyJ785E6bR2sTWyXV5/OWjSGVGss4OkPx/9DYJKkudyiBKlLWuu', 'role': 'ADMIN'},
            {'login': 'maria',    'password': '$2b$12$pMoyJ785E6bR2sTWyXV5/OWjSGVGss4OkPx/9DYJKkudyiBKlLWuu', 'role': 'USER'},
        ]
    )

    recipes_table = sa.table(
        'recipes',
        sa.column('title', sa.String),
        sa.column('cooking_time', sa.Integer),
        sa.column('content', sa.String),
        sa.column('user_id', sa.Integer),
        sa.column('cuisine_id', sa.Integer),
        sa.column('dish_type_id', sa.Integer)
    )
    op.bulk_insert(
        recipes_table,
        [
            {
                'title': 'Паста Карбонара',
                'cooking_time': 30,
                'content': 'Ингредиенты: паста, сливки. Готовить пока не приготовится.',
                'user_id': 1,
                'cuisine_id': 1,
                'dish_type_id': 3,
            },
            {
                'title': 'Куриный суп с вермишелью',
                'cooking_time': 45,
                'content': 'Ингредиенты: курица, вода. Готовить пока не приготовится.',
                'user_id': 2,
                'cuisine_id': 3,
                'dish_type_id': 1,
            },
            {
                'title': 'Салат Цезарь',
                'cooking_time': 20,
                'content': 'Салат с курицей, пармезаном и соусом Цезарь. Перемешать тщательно.',
                'user_id': 3,
                'cuisine_id': 1,
                'dish_type_id': 2,
            },
            {
                'title': 'Суши с лососем',
                'cooking_time': 60,
                'content': 'Свежие суши с лососем и овощами. Нужна рыба и овощи.',
                'user_id': 4,
                'cuisine_id': 4,
                'dish_type_id': 3,
            },
            {
                'title': 'Хачапури по-аджарски',
                'cooking_time': 50,
                'content': 'Грузинское блюдо с сыром и яичным соусом. Пальчики оближешь. Берете сначала 3 тонны сыра, потом желточек.',
                'user_id': 5,
                'cuisine_id': 5,
                'dish_type_id': 3,
            },
            {
                'title': 'Борщ',
                'cooking_time': 90,
                'content': 'Традиционный русский борщ со свеклой и сметаной. Надо купить говядину, потом долго варить.',
                'user_id': 6,
                'cuisine_id': 3,
                'dish_type_id': 1,
            },
        ]
    )

    recipe_hashtags_table = sa.table(
        'recipe_hashtags',
        sa.column('recipe_id', sa.Integer),
        sa.column('hashtag_id', sa.Integer)
    )
    op.bulk_insert(
        recipe_hashtags_table,
        [
            {'recipe_id': 1, 'hashtag_id': 2},
            {'recipe_id': 1, 'hashtag_id': 3},
            {'recipe_id': 2, 'hashtag_id': 1},
            {'recipe_id': 2, 'hashtag_id': 5},
            {'recipe_id': 3, 'hashtag_id': 3},
            {'recipe_id': 3, 'hashtag_id': 4},
            {'recipe_id': 4, 'hashtag_id': 2},
            {'recipe_id': 4, 'hashtag_id': 4},
            {'recipe_id': 5, 'hashtag_id': 1},
            {'recipe_id': 5, 'hashtag_id': 6},
            {'recipe_id': 6, 'hashtag_id': 5},
            {'recipe_id': 6, 'hashtag_id': 6},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE * FROM recipe_hashtags")
    op.execute("DELETE * FROM recipes")
    op.execute("DELETE * FROM dish_types")
    op.execute("DELETE * FROM cuisines")
    op.execute("DELETE * FROM hashtags")
    op.execute("DELETE * FROM users")
    # ### end Alembic commands ###
