"""cascade delete

Revision ID: efa733b577e8
Revises: dbc393d54f8a
Create Date: 2025-04-27 18:03:39.846729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa733b577e8'
down_revision: Union[str, None] = 'dbc393d54f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_hashtags_hashtag_id_fkey', 'recipe_hashtags', type_='foreignkey')
    op.drop_constraint('recipe_hashtags_recipe_id_fkey', 'recipe_hashtags', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_hashtags', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe_hashtags', 'hashtags', ['hashtag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_hashtags', type_='foreignkey')
    op.drop_constraint(None, 'recipe_hashtags', type_='foreignkey')
    op.create_foreign_key('recipe_hashtags_recipe_id_fkey', 'recipe_hashtags', 'recipes', ['recipe_id'], ['id'])
    op.create_foreign_key('recipe_hashtags_hashtag_id_fkey', 'recipe_hashtags', 'hashtags', ['hashtag_id'], ['id'])
    # ### end Alembic commands ###
