version: "3.8"
services:
  recipes-app:
    container_name: recipes-app
    build: .
    depends_on:
      - recipes-db
    environment:
      DB_HOST: recipes-db
      DB_PORT: "5432"
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      SECRET_KEY: "skdjskaldjfksiekfdjcncbxmsi123"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8080:8080"
  recipes-db:
    container_name: recipes-database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./mount/database/recipes:/var/lib/postgresql/data
    ports:
      - "5432:5432"
